In [1]:
import pandas as pd
from pathlib import Path
import seaborn as sns
%matplotlib inline

In [2]:
#SET VOLCANO PATH, ALL VOLCANO DATA
Volcanoes_df = Path("Resources/The_Volcanoes_Of_Earth.csv")
Volcanoes_df = pd.read_csv(Volcanoes_df)

In [3]:
Volcanoes_df.head()

,Volcano_Name,Volcano_Image,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Summit_and_Elevatiuon,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km
0,Abu,https://volcano.si.edu/gallery/photos/GVP-0895...,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,"641 m, 2103 ft",34.5°N,131.6°E,3597.0,9594.0,117805.0,4071152.0
1,Acamarachi,https://volcano.si.edu/gallery/photos/GVP-0688...,Stratovolcano,Chile,South America,"Northern Chile, Bolivia and Argentina",holocene,Unknown - Evidence Credible,"6023 m, 19760 ft",23.292°S,67.618°W,0.0,7.0,294.0,9092.0
2,Acatenango,https://volcano.si.edu/gallery/photos/GVP-0788...,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,"3976 m, 13045 ft",14.501°N,90.876°W,4329.0,60730.0,1042836.0,7634778.0
3,Acigol-Nevsehir,https://volcano.si.edu/includes/images/noimage...,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,"1683 m, 5522 ft",38.537°N,34.621°E,127863.0,127863.0,218469.0,2253483.0
4,Adams,https://volcano.si.edu/gallery/photos/GVP-0281...,Stratovolcano,United States,Canada and Western USA,USA (Washington),holocene,950 CE,"3742 m, 12277 ft",46.206°N,121.49°W,0.0,70.0,4019.0,393303.0

In [4]:
#DETERMINE DATA TYPES
Volcanoes_df.dtypes

Volcano_Name                object
Volcano_Image               object
Volcano_Type                object
Country                     object
Region                      object
Subregion                   object
epoch_period                object
Last_Eruption               object
Summit_and_Elevatiuon       object
Latitude                    object
Longitude                   object
population_within_5km      float64
population_within_10km     float64
population_within_30km     float64
population_within_100km    float64
dtype: object

In [5]:
#SETTING NEW VARIABLE FOR VOLCANO NAMES AND BASIC STATS, 
#SETTING IT UP TO COMPARE TO EARTHQUAKES
Volcano_Names = Path("Resources/The_Volcanoes_Of_Earth.csv")
Volcano_Names = pd.read_csv(Volcano_Names, index_col="Volcano_Name")
Volcano_Names.head()

,Volcano_Image,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Summit_and_Elevatiuon,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km
Volcano_Name,,,,,,,,,,,,,,
Abu,https://volcano.si.edu/gallery/photos/GVP-0895...,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,"641 m, 2103 ft",34.5°N,131.6°E,3597.0,9594.0,117805.0,4071152.0
Acamarachi,https://volcano.si.edu/gallery/photos/GVP-0688...,Stratovolcano,Chile,South America,"Northern Chile, Bolivia and Argentina",holocene,Unknown - Evidence Credible,"6023 m, 19760 ft",23.292°S,67.618°W,0.0,7.0,294.0,9092.0
Acatenango,https://volcano.si.edu/gallery/photos/GVP-0788...,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,"3976 m, 13045 ft",14.501°N,90.876°W,4329.0,60730.0,1042836.0,7634778.0
Acigol-Nevsehir,https://volcano.si.edu/includes/images/noimage...,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,"1683 m, 5522 ft",38.537°N,34.621°E,127863.0,127863.0,218469.0,2253483.0
Adams,https://volcano.si.edu/gallery/photos/GVP-0281...,Stratovolcano,United States,Canada and Western USA,USA (Washington),holocene,950 CE,"3742 m, 12277 ft",46.206°N,121.49°W,0.0,70.0,4019.0,393303.0

In [6]:
#DETERMINING VOLCANO NAMES 
Volcano_Names = Volcano_Names[['Volcano_Type', 'Region', 'Last_Eruption']]
Volcano_Names.head()

,Volcano_Type,Region,Last_Eruption
Volcano_Name,,,
Abu,Shield(s),"Japan, Taiwan, Marianas",6850 BCE
Acamarachi,Stratovolcano,South America,Unknown - Evidence Credible
Acatenango,Stratovolcano(es),México and Central America,1972 CE
Acigol-Nevsehir,Caldera,Mediterranean and Western Asia,2080 BCE
Adams,Stratovolcano,Canada and Western USA,950 CE

In [7]:
Volcano_Names.tail()

                           Volcano_Type           Region Last_Eruption
Volcano_Name
Zarechny                     Caldera(s)  Volcanic Region   Pleistocene
Zenikame                      Submarine  Volcanic Region   Pleistocene
Zheltiy                   Stratovolcano  Volcanic Region   Pleistocene
Zhupanovskiye Vostriyaky  Stratovolcano  Volcanic Region   Pleistocene
Zikwala                   Stratovolcano  Volcanic Region   Pleistocene

In [8]:
Volcano_Names['Region'].value_counts()

Region
Volcanic Region                   1318
South America                      179
Japan, Taiwan, Marianas            134
Indonesia                          126
Africa and Red Sea                 119
México and Central America         109
Kamchatka and Mainland Asia         86
Alaska                              83
Melanesia and Australia             73
Canada and Western USA              64
New Zealand to Fiji                 56
Philippines and SE Asia             46
Kuril Islands                       44
Middle East and Indian Ocean        42
Mediterranean and Western Asia      41
Iceland and Arctic Ocean            36
Hawaii and Pacific Ocean            33
Atlantic Ocean                      28
Antarctica                          28
West Indies                         16
Name: count, dtype: int64

In [ ]:
###ADDING EARTHQUAKES

In [9]:
Earthquakes_df = Path("Resources/earthquake_1995-2023.csv")
Earthquakes_df = pd.read_csv(Earthquakes_df)

In [10]:
Earthquakes_df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

#VARIABLES IN COMMON BETWEEN THE TWO DATASETS:
#